apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: uasis
  name: 172.16.0.244-geoserver-logs
  labels:
    uygulama: geoserver
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.0.244
    path: "/data/nfs/kubernetes/pvs/geoserver-logs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: uasis
  name: geoserver-logs-claim
spec:
  selector:
    matchLabels:
      uygulama: geoserver
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi


